# Generated by Django 3.1.1 on 2020-10-26 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_school_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_fee',
            name='student',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students'),
            preserve_default=False,
        ),
    ]
