# Generated by Django 3.1.1 on 2020-10-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_school_fee_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_fee',
            name='receipt_id',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
    ]
